logistikk:
  image: mesanfagark/reaktiv-logistikk
  ports:
    - "9999:9999"
isolat:
  image: mesanfagark/reaktiv-isolat
  net : "host"
  ports:
    - "9998:9998"
fangeregister:
  image: mesanfagark/fag-ark-persistering-fangereg
  ports: 
    - "49000:8080"
  links: 
    - mongo
mongo:
  image: mongo:3.0.1

